// Copyright 2026 The Lynxtron Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

// Build tool for the Lynxtron js2c bundles. The Node snapshot already caches
// these bundles in native builds, except node_init's custom wrapper. Generate
// all three so cross-architecture builds work without Node's code cache too.

#include <cstdint>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "libplatform/libplatform.h"
#include "shell/common/js2c_bundle_ids.h"
#include "third_party/node/src/env.h"
#include "third_party/node/src/node_builtins.h"
#include "third_party/node/src/node_snapshot_builder.h"
#include "v8/include/v8.h"

namespace {

struct CacheEntry {
  std::string id;
  std::vector<uint8_t> bytes;
  bool custom_wrapper;
};

}  // namespace

int main(int argc, char* argv[]) {
  if (argc != 4 || (std::string_view(argv[2]) != "all" &&
                    std::string_view(argv[2]) != "node-init-only")) {
    std::cerr << "usage: js2c_code_cache <out.cc> <all|node-init-only> "
                 "<v8-flags>\n";
    return 1;
  }
  const bool include_standard_bundles = std::string_view(argv[2]) == "all";

  const node::SnapshotData* snapshot =
      node::SnapshotBuilder::GetEmbeddedSnapshotData();
  if (!snapshot) {
    std::cerr << "embedded Node snapshot is required\n";
    return 1;
  }

  v8::V8::InitializeICUDefaultLocation(argv[0]);
  v8::V8::SetSnapshotDataBlob(
      const_cast<v8::StartupData*>(&snapshot->v8_snapshot_blob_data));
  v8::V8::SetFlagsFromString(argv[3]);
  std::unique_ptr<v8::Platform> platform = v8::platform::NewDefaultPlatform();
  v8::V8::InitializePlatform(platform.get());
  v8::V8::Initialize();

  v8::Isolate::CreateParams params;
  params.array_buffer_allocator =
      v8::ArrayBuffer::Allocator::NewDefaultAllocator();
  node::SnapshotBuilder::InitializeIsolateParams(snapshot, &params);
  v8::Isolate* isolate = v8::Isolate::New(params);
  std::vector<CacheEntry> caches;
  {
    v8::Isolate::Scope isolate_scope(isolate);
    v8::HandleScope handle_scope(isolate);
    v8::Local<v8::Context> context =
        v8::Context::FromSnapshot(isolate, 0).ToLocalChecked();
    v8::Context::Scope context_scope(context);

    node::builtins::BuiltinLoader loader;
    loader.SetEagerCompile();
    for (const char* id :
         {lynxtron::js2c::kBrowserInitId, lynxtron::js2c::kLynxBtsInitId,
          lynxtron::js2c::kNodeInitId}) {
      const bool custom_wrapper =
          std::string_view(id) == lynxtron::js2c::kNodeInitId;
      if (!include_standard_bundles && !custom_wrapper) {
        continue;
      }
      v8::Local<v8::Function> function;
      if (custom_wrapper) {
        auto parameters = lynxtron::js2c::MakeNodeInitParams(isolate);
        if (!loader.LookupAndCompile(context, id, &parameters, nullptr)
                 .ToLocal(&function)) {
          std::cerr << "failed to compile " << id << '\n';
          return 1;
        }
      } else if (!loader.LookupAndCompile(context, id, nullptr)
                      .ToLocal(&function)) {
        std::cerr << "failed to compile " << id << '\n';
        return 1;
      }
      std::unique_ptr<v8::ScriptCompiler::CachedData> cache(
          v8::ScriptCompiler::CreateCodeCacheForFunction(function));
      if (!cache || cache->length == 0) {
        std::cerr << "failed to produce code cache for " << id << '\n';
        return 1;
      }
      caches.push_back(
          {id, {cache->data, cache->data + cache->length}, custom_wrapper});
    }
  }

  std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
  if (!out) {
    std::cerr << "failed to open " << argv[1] << '\n';
    return 1;
  }
  out << "// Generated by js2c_code_cache. Do not edit.\n"
      << "#include \"shell/common/js2c_code_cache.h\"\n"
      << "#include \"third_party/node/src/node_builtins.h\"\n\n"
      << "namespace lynxtron {\n";
  for (size_t entry = 0; entry < caches.size(); ++entry) {
    out << "static const uint8_t kCache" << entry << "[] = {";
    for (size_t i = 0; i < caches[entry].bytes.size(); ++i) {
      if (i % 32 == 0) {
        out << "\n  ";
      }
      out << static_cast<unsigned>(caches[entry].bytes[i]) << ',';
    }
    out << "\n};\n";
  }
  for (bool custom_wrapper : {false, true}) {
    out << "const std::vector<node::builtins::CodeCacheInfo>& "
        << (custom_wrapper ? "Js2cCustomWrapperCodeCache"
                           : "Js2cStandardWrapperCodeCache")
        << "() {\n"
        << "  static const std::vector<node::builtins::CodeCacheInfo> cache = "
           "{\n";
    for (size_t entry = 0; entry < caches.size(); ++entry) {
      if (caches[entry].custom_wrapper != custom_wrapper) {
        continue;
      }
      out << "      {\"" << caches[entry].id
          << "\", node::builtins::BuiltinCodeCacheData(kCache" << entry
          << ", sizeof(kCache" << entry << "))},\n";
    }
    out << "  };\n"
        << "  return cache;\n"
        << "}\n";
  }
  out << "}  // namespace lynxtron\n";
  if (!out) {
    std::cerr << "failed to write " << argv[1] << '\n';
    return 1;
  }

  isolate->Dispose();
  v8::V8::Dispose();
  v8::V8::DisposePlatform();
  delete params.array_buffer_allocator;
  return 0;
}
